# This file was generated by GoReleaser. DO NOT EDIT.
class Ddf < Formula
  desc "CLI tool to De-Duplicate Files"
  homepage "https://github.com/wtait1/ddf"
  version "0.0.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/wtait1/ddf/releases/download/v0.0.2/ddf_0.0.2_Darwin_amd64.tar.gz"
    sha256 "702809385b83fc4370f57134882a6f579641b4f089b4ee2f2b685d0b1b57f126"
  elsif OS.linux?
  end

  def install
    bin.install "ddf"
  end

  test do
    system "#{bin}/ddf -v"
  end
end
